In [ ]:
import config as cfg
import open3d as o3d
import numpy as np
pcd = o3d.io.read_point_cloud(cfg.OUTPUT_DIR + "/scene.pcd")

# Print values of the point cloud after numpy conversion
print(pcd)
print(np.asarray(pcd.points))
# Max and min values of the point cloud
distances = [np.linalg.norm(p) for p in np.asarray(pcd.points)]
print('Max:', np.max(distances))
print('Min:', np.min(distances))


In [ ]:
import open3d as o3d

# Load the .glb file
mesh = o3d.io.read_triangle_mesh("temp_test/scene.glb")

# Visualize the .glb file
o3d.visualization.draw_geometries([mesh])


In [1]:
import numpy as np

# Define the homogeneous transformation matrices
slam_L = np.array([
    [ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
    [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00, -4.16333634e-17],
    [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00, -1.04083409e-17],
    [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000000e+00]
])

slam_R = np.array([
    [ 0.99836471, -0.03532317,  0.04494634,  0.00567676],
    [ 0.05208901,  0.23820291, -0.96981757, -0.11215309],
    [ 0.02355068,  0.97057285,  0.23965332, -0.08683892],
    [ 0.0, 0.0, 0.0, 1.0]
])

rgb = np.array([
    [ 0.99339134, -0.05150564,  0.10257099, -0.00428072],
    [ 0.10364322,  0.78649219, -0.60884162, -0.01184173],
    [-0.04931251,  0.61544878,  0.78663275, -0.00511398],
    [ 0.0, 0.0, 0.0, 1.0]
])

# Convert to relative transformations with respect to slam_L
def extract_relative_pose(base_pose, other_pose):
    return np.linalg.inv(base_pose).dot(other_pose)

# Calculate relative transformations
relative_slam_R = extract_relative_pose(slam_L, slam_R)
relative_rgb = extract_relative_pose(slam_L, rgb)

# Output the relative transformations
print("Relative Transformation (slam-R with respect to slam-L):")
print(relative_slam_R)

print("\nRelative Transformation (RGB with respect to slam-L):")
print(relative_rgb)


Relative Transformation (slam-R with respect to slam-L):
[[ 0.99836471 -0.03532317  0.04494634  0.00567676]
 [ 0.05208901  0.23820291 -0.96981757 -0.11215309]
 [ 0.02355068  0.97057285  0.23965332 -0.08683892]
 [ 0.          0.          0.          1.        ]]

Relative Transformation (RGB with respect to slam-L):
[[ 0.99339134 -0.05150564  0.10257099 -0.00428072]
 [ 0.10364322  0.78649219 -0.60884162 -0.01184173]
 [-0.04931251  0.61544878  0.78663275 -0.00511398]
 [ 0.          0.          0.          1.        ]]


In [ ]:
# For SLAM-R what is the translation in meters and the rotation in degrees around the z-axis?

def get_translation_and_rotation(matrix):
    translation = matrix[:3, 3]
    rotation = np.degrees(np.arctan2(matrix[1, 0], matrix[0, 0]))
    return translation, rotation
